# MPS Integration
# http://IP:5267/sclip/web-service/[subscribe|receive-result|get-content|mo-listener]
web:
  image: anapsix/alpine-java
  environment:
    TZ: 'Asia/Ho_Chi_Minh'
  volumes:
    - ./target:/root
  command: /root/run.sh
